"""Generate a static, public architectural brochure from shared verified content."""
from html import escape
from urllib.parse import quote
import json, zipfile
from project_data import *
D = PUBLIC
D.mkdir(parents=True,exist_ok=True)

def mail(subject='Prohlídka Viladům v zahradách'):
 return 'mailto:'+EMAIL+'?subject='+quote(subject)

def figure(name,label,kind='',caption=True):
 ext='svg' if name=='15-house-photo' else ('png' if name.startswith(('plan-','section-','scale-')) or name in ('site','garden') else 'webp')
 return f'<figure class="media {kind}"><button class="image" data-full="assets/{name}.{ext}" aria-label="Zvětšit: {escape(label)}"><img src="assets/{name}.{ext}" alt="{escape(label)}" loading="lazy" decoding="async"></button>{f"<figcaption>{escape(label)}</figcaption>" if caption else ""}</figure>'

def apartment(u):
 a,floor,layout,total,photos,rooms,sections=u;k=a.lower();title,description,facts=CHARACTERS[a]
 stats=''.join(f'<div><strong>{v}</strong><span>{label}</span></div>' for v,label in facts)
 table=''.join(f'<tr><td>{number}</td><th scope="row">{room}</th><td>{area}</td></tr>' for number,room,area in rooms)
 floorplan='plan-second' if a in 'ABC' else 'plan-attic'
 gallery=''.join(figure(n,f'Byt {a} / {label} · vizualizace, návrh vybavení') for n,label in photos)
 loft=f'<p class="small-note">{LOFT_NOTE}</p>' if a in 'DE' else ''
 return f'''<article id="byt-{k}" class="apartment section">
 <div class="apartment-title"><div><span class="eyebrow">{floor} / Byt {a}</span><h3>{title}</h3></div><div class="unit-identity"><span>{a}</span><div><strong>{layout.replace(' + ','+')}</strong><b>{total} m²</b><small>celkem dle projektu</small></div></div></div>
 <p class="unit-description">{description}</p><div class="unit-stats">{stats}</div>
 <div class="unit-layout"><div class="plan-stage">{figure('archviz-'+k,f'Materiálový půdorys bytu {a} · návrh vybavení','archviz',False)}<div class="plan-caption"><span>Materiálový půdorys / návrh vybavení</span><span>Zvětšit kliknutím</span></div>{loft}
 <details class="technical"><summary>Projektový půdorys, řezy a poloha v domě</summary>{figure('plan-'+k,'Původní projektový půdorys bytu '+a,'drawing')}<div class="technical-sections">{''.join(figure(s,'Projektový řez bytem '+a,'drawing') for s in sections)}</div>{figure('scale-'+k,'Orientace a měřítko z původního výkresu','scale')}{figure(floorplan,'Poloha bytu v projektovém podlaží','drawing')}{figure('plan-loft','Projektové loftové podlaží','drawing') if a in 'DE' else ''}</details></div>
 <div class="room-panel"><span class="eyebrow">Dispozice v číslech</span><h4>Každý metr<br>má své místo.</h4><table><caption class="sr-only">Místnosti bytu {a} dle původní tabulky</caption><thead><tr><th>Číslo</th><th>Místnost</th><th>m²</th></tr></thead><tbody>{table}</tbody><tfoot><tr><th colspan="2">Celkem dle projektu</th><td>{total}</td></tr></tfoot></table><a class="button dark" href="{mail('Zájem o byt '+a+' / Viladům v zahradách')}">Získat nabídku bytu {a}</a><p class="small-note">Cena, aktuální dostupnost a prohlídka na vyžádání.</p></div></div>
 <div class="unit-gallery {'two' if len(photos)>1 else ''}">{gallery}</div></article>'''

cards=''.join(f'''<a class="unit-card" data-floor="{'second' if u[0] in 'ABC' else 'attic'}" href="#byt-{u[0].lower()}"><div class="card-heading"><span class="card-letter">{u[0]}</span><span>{u[1]}</span></div><img src="assets/archviz-{u[0].lower()}.webp" alt="Materiálový půdorys bytu {u[0]}, návrh vybavení" loading="lazy" width="440" height="250"><div class="card-data"><strong>{u[2].replace(' + ','+')}</strong><strong>{u[3]} <small>m²</small></strong></div><p>{CHARACTERS[u[0]][0]}</p><span class="card-action">Detail bytu {u[0]}</span></a>''' for u in UNITS)
places=''.join(f'''<article class="place"><span class="place-number">{number}</span><h3>{name}</h3><p>{desc}</p><div><a href="{url}" target="_blank" rel="noopener">Web místa</a><a href="https://mapy.com/cs/zakladni?q={quote(query)}" target="_blank" rel="noopener">Ukázat na mapě</a></div></article>''' for number,name,desc,url,query in PLACES)
source_links=''.join(f'<li><a href="{url}" target="_blank" rel="noopener">{label}</a></li>' for label,url in SOURCES)
questions=''.join(f'<details><summary>{q}</summary><p>{a}</p></details>' for q,a in FAQ)

head=f'''<!doctype html><html lang="cs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#20382f"><title>Viladům v zahradách | Šest osobitých bytů v Lounech</title><meta name="description" content="Historický dům a šest velkorysých bytů v Lounech. Prohlédněte si dispozice 82,25–116,45 m² dle projektu, návrh zahrady a domluvte si prohlídku."><link rel="canonical" href="{SITE_URL}/"><meta property="og:type" content="website"><meta property="og:locale" content="cs_CZ"><meta property="og:title" content="Viladům v zahradách | Louny"><meta property="og:description" content="{MAIN_LINE} Šest bytů o 82,25–116,45 m² dle projektu."><meta property="og:url" content="{SITE_URL}/"><meta property="og:image" content="{SITE_URL}/assets/social-card.png"><meta property="og:image:alt" content="Viladům v zahradách, Louny. Historie v architektuře. Prostor pro váš život."><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="Viladům v zahradách | Louny"><meta name="twitter:description" content="{MAIN_LINE}"><meta name="twitter:image" content="{SITE_URL}/assets/social-card.png"><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 40 40'%3E%3Crect width='40' height='40' fill='%2320382f'/%3E%3Ctext x='20' y='29' text-anchor='middle' fill='%23f5f2e9' font-family='Georgia' font-size='30'%3EV%3C/text%3E%3C/svg%3E"><link rel="stylesheet" href="style.css"></head><body>'''
body=f'''<a class="skip" href="#obsah">Přejít na obsah</a>
<header class="site-header"><a class="wordmark" href="#uvod" aria-label="Viladům v zahradách, úvod">Viladům<span>v zahradách</span></a><nav aria-label="Hlavní navigace"><a href="#dum">Dům</a><a href="#zahrada">Zahrada</a><a href="#vyber">Byty</a><a href="#louny">Louny</a><a href="#kontakt">Kontakt</a></nav><a class="header-cta" href="{mail()}">Domluvit prohlídku</a><button class="menu-toggle" aria-expanded="false" aria-controls="mobile-menu">Menu</button></header>
<nav id="mobile-menu" class="mobile-menu" aria-label="Mobilní navigace" hidden><a href="#dum">Dům</a><a href="#zahrada">Zahrada</a><a href="#vyber">Vybrat byt</a><a href="#louny">Louny</a><a href="#doprava">Praha a doprava</a><a href="#kontakt">Kontakt</a><a href="brozura.pdf" download>Stáhnout brožuru</a></nav>
<main id="obsah"><section id="uvod" class="hero"><div class="hero-copy"><span class="eyebrow">Osvoboditelů 497 / Louny</span><h1>Historie<br>v architektuře.<br><em>Prostor</em><br>pro váš život.</h1><p>Viladům v zahradách. Historický dům, velkorysé dispozice a nový příběh bydlení v Lounech.</p><div class="hero-actions"><a class="button dark" href="#vyber">Vybrat svůj byt</a><a class="text-link" href="brozura.pdf" download>Stáhnout brožuru</a></div><div class="hero-bottom"><span>Viladům v zahradách</span><span>Edice / 2026</span></div></div><figure class="hero-photo"><button class="image" data-full="assets/15-house-photo.svg" aria-label="Zvětšit skutečnou fotografii domu"><img src="assets/15-house-photo.svg" alt="Skutečná fotografie žluté historické fasády Viladomu v zahradách" fetchpriority="high" width="1419" height="1238"></button><figcaption><span>Architektura, která má příběh.</span><span>Skutečná fotografie domu</span></figcaption></figure></section>
<div class="project-facts"><div><strong>6</strong><span>bytů v projektu</span></div><div><strong>82,25–116,45 <small>m²</small></strong><span>celkem dle projektu</span></div><div><strong>3+kk / 4+kk / loft</strong><span>různé podoby domova</span></div><div><strong>Louny</strong><span>Osvoboditelů 497</span></div></div>
<section id="dum" class="story section"><div class="section-heading"><span class="eyebrow">01 / Dům</span><h2>Dům s minulostí.<br><em>Život před vámi.</em></h2></div><div class="story-grid"><div class="story-copy"><p class="lead">{STORY}</p><p>{SECOND}</p><p>V podkroví dostává bydlení jiný výraz: střešní světlo, krov a loftová úroveň u vybraných bytů.</p><a class="text-link" href="{SOURCES[1][1]}" target="_blank" rel="noopener">Architektonický koncept</a></div>{figure('01-living','Obytný prostor / vizualizace, návrh vybavení','story-image')}</div><div class="reconstruction"><span class="eyebrow">Proměna domu</span><h3>Charakter zůstává.<br>Domov získává nový rozměr.</h3><p>{RECONSTRUCTION}</p><a class="text-link" href="{mail('Standard a stav rekonstrukce / Viladům')}">Zjistit standard a stav rekonstrukce</a></div></section>
<section id="zahrada" class="garden-band"><div class="section"><div class="section-heading"><span class="eyebrow">02 / Zahrada</span><h2>Za dveřmi město.<br><em>Za domem zahrada.</em></h2></div><div class="garden-grid"><div><p class="lead">{GARDEN}</p><p>Ranní káva, chvíle s knihou, návrat z města. Návrh zahradního prostředí přidává bydlení další rozměr.</p><div class="garden-labels"><span>Zeleň vnitrobloku</span><span>Pobytová místa v návrhu</span><span>Návaznost na dům</span></div><p class="small-note">{GARDEN_NOTE}</p><a class="text-link" href="{mail('Zahrada, terasa a parkování / Viladům')}">Zjistit podmínky užívání</a></div>{figure('garden','Krajinářský návrh z původní projektové brožury','garden-drawing')}</div><details class="garden-technical"><summary>Prohlédnout celkovou situaci projektu</summary>{figure('site','Původní projektová situace; nevyjadřuje potvrzený aktuální stav','drawing')}</details></div></section>
<section id="vyber" class="selection section"><div class="section-heading"><span class="eyebrow">03 / Vyberte svůj byt</span><h2>Šest adres<br><em>uvnitř jednoho příběhu.</em></h2><p>Ve druhém podlaží světlo a historická okna. Pod střechou osobitý charakter a dvě loftové dispozice. Který prostor bude váš?</p></div><div class="filter-row"><div role="group" aria-label="Vybrat podlaží"><button data-filter="all" aria-pressed="true">Všechny byty</button><button data-filter="second" aria-pressed="false">2. nadzemní podlaží</button><button data-filter="attic" aria-pressed="false">Podkroví</button></div><span id="selection-count" aria-live="polite">6 bytů v projektu</span></div><div class="unit-grid">{cards}</div><p class="small-note">{AREA_NOTE} Cenu a dostupnost získáte přímo u kontaktu projektu.</p></section>
<section class="apartment-collection" aria-label="Detaily bytů"><div class="collection-heading section"><span class="eyebrow">Vaše budoucí bydlení / Byty A–C</span><h2>Prostor. Světlo.<br><em>Klidný charakter.</em></h2><div class="unit-jumps"><a href="#byt-a">Byt A</a><a href="#byt-b">Byt B</a><a href="#byt-c">Byt C</a></div></div>{''.join(apartment(u) for u in UNITS[:3])}</section>
<section id="podkrovi" class="attic-band"><div class="section"><span class="eyebrow">Vaše budoucí bydlení / Byty D–F</span><h2>Pod střechou.<br><em>Nad běžným.</em></h2><p>{ATTIC}</p><div class="unit-jumps"><a href="#byt-d">Byt D</a><a href="#byt-e">Byt E</a><a href="#byt-f">Byt F</a></div></div>{figure('06-loft','Podkrovní koncept / vizualizace, návrh vybavení','attic-panorama')}<div class="attic-pair section">{figure('07-loft-kitchen','Podkrovní kuchyň / vizualizace, návrh vybavení')}{figure('08-loft-dining','Podkrovní jídelna / vizualizace, návrh vybavení')}</div></section>
<section class="apartment-collection" aria-label="Detaily podkrovních bytů">{''.join(apartment(u) for u in UNITS[3:])}</section>
<section class="floor-section section"><span class="eyebrow">Dům v souvislostech</span><h2>Jak do sebe<br><em>prostory zapadají.</em></h2><details><summary>2. nadzemní podlaží / A, B, C</summary>{figure('plan-second','Původní dispozice 2. nadzemního podlaží','drawing')}</details><details><summary>Podkroví / D, E, F</summary>{figure('plan-attic','Původní dispozice podkroví','drawing')}</details><details><summary>Loft / D, E</summary>{figure('plan-loft','Původní dispozice loftů','drawing')}</details></section>
<section id="louny" class="city-band"><div class="section"><div class="city-title"><div><span class="eyebrow">04 / Louny</span><h2>Malé město.<br><em>Velký prostor pro život.</em></h2></div><p>Večer v divadle. Ráno u řeky. Umění, plavání a káva po cestě. Louny mají vlastní kulturní život, historické centrum a krajinu, do které se chcete vracet.</p></div><div class="places-grid">{places}</div><div class="city-practical"><div><h3>Rodina a běžný den</h3><p>Školy, školky a městské služby zjistíte v aktuálním přehledu města. Obchody, kavárny a další služby si můžete projít při návštěvě Loun.</p><a class="text-link" href="https://www.mulouny.cz/" target="_blank" rel="noopener">Město a jeho služby</a></div><div><h3>Víkend venku</h3><p>Podél Ohře na kole. Do krajiny Rané a Oblíku na výlet. Městská zeleň a okolí Českého středohoří nabízejí rozdílné tempo pro každý den.</p><a class="text-link" href="https://www.louny.eu/cz/cykloturistika-v-okoli-mesta-louny/389/" target="_blank" rel="noopener">Trasy a výlety v okolí</a></div></div><div class="local-evidence"><div><strong>≈ 140 mil. Kč</strong><p>Schválený plán města na výstavbu v roce 2026, včetně investic do škol a veřejných prostor. Jde o plán, nikoli soupis dokončených staveb.</p><a href="{SOURCES[5][1]}" target="_blank" rel="noopener">Investiční plán města</a></div><div><strong>5 207</strong><p>Zaměstnanců v průmyslové zóně Triangle k 31. 12. 2025. Konkrétní doklad pracovního zázemí širšího regionu.</p><a href="{SOURCES[-1][1]}" target="_blank" rel="noopener">Údaj správy Triangle</a></div></div><a class="button outline" href="https://mapy.com/cs/zakladni?q={quote(PROJECT_ADDRESS)}" target="_blank" rel="noopener">Navigovat k domu</a></div></section>
<section id="doprava" class="transport section"><span class="eyebrow">05 / Praha a doprava</span><div class="transport-title"><h2>Praha blíž.<br><em>Váš život po svém.</em></h2><p>Zlepšující se spojení otevírá prostor pro život mezi městem, prací a domovem. Hlavní hodnotou Loun přitom zůstávají Louny samotné.</p></div><div class="transport-grid"><div class="timeline"><div><span>2023</span><h3>Obchvat Loun</h3><p>Zkapacitněný dálniční úsek v provozu od září.</p></div><div><span>2024</span><h3>Chlumčany</h3><p>Navazující úsek zprovozněný v červnu.</p></div><div><span>2026</span><h3>Výstavba pokračuje</h3><p>Od září provoz na části nového pásu u Knovíze, v této etapě v režimu 1+1.</p></div><div class="planned"><span>2027 / plán</span><h3>Tři středočeské úseky</h3><p>Knovíz–Slaný-západ, Slaný-západ–Kutrovice a Kutrovice–Panenský Týnec. Plánovaný termín se může změnit.</p></div></div><div class="public-transport"><span class="eyebrow">Spojení veřejnou dopravou</span><strong class="route-number">389</strong><h3>Louny<br>Slaný<br>Praha, Nádraží Veleslavín</h3><p>{PID_TEXT}</p><a class="button light" href="{SOURCES[4][1]}" target="_blank" rel="noopener">Aktuální jízdní řády PID</a><p class="small-note">Doba cesty závisí na konkrétním spoji, cíli a dopravní situaci.</p></div></div><div class="transport-sources"><span>Stav ověřen {VERIFIED}. „Praha blíž“ vyjadřuje vývoj dopravního spojení.</span><a href="{SOURCES[2][1]}" target="_blank" rel="noopener">Přehled D7</a><a href="{SOURCES[3][1]}" target="_blank" rel="noopener">Zpráva ŘSD</a></div></section>
<section id="standard" class="faq-section section"><div><span class="eyebrow">06 / Standard a další kroky</span><h2>Dobré rozhodnutí<br><em>začíná podrobnostmi.</em></h2><p>Prohlédněte si konkrétní byt. Získejte aktuální nabídku, standard dodávky a podklady pro klidné rozhodnutí.</p><ol class="purchase-steps"><li><span>01</span>Vybrat byt</li><li><span>02</span>Získat nabídku a prohlídku</li><li><span>03</span>Projít standard a dokumentaci</li></ol></div><div class="faq-list">{questions}</div></section>
<section id="kontakt" class="contact-band"><div class="section"><span class="eyebrow">07 / Váš další krok</span><h2>Tenhle příběh<br><em>může být váš.</em></h2><div class="contact-grid"><div><p>Vyberte si byt a domluvte prohlídku. Projdeme s vámi dispozici, aktuální nabídku i všechny důležité podrobnosti.</p><div class="contact-actions"><a class="button light" href="{mail()}">Domluvit prohlídku</a><a class="text-link" href="brozura.pdf" download>Stáhnout celou brožuru</a></div></div><address><span>Adresa projektu</span><a class="project-address" href="https://mapy.com/cs/zakladni?q={quote(PROJECT_ADDRESS)}" target="_blank" rel="noopener">{PROJECT_ADDRESS}</a><span>Kontakt projektu / Jan Čáka</span><a href="tel:+420774320438">{PHONE}</a><a href="mailto:{EMAIL}">{EMAIL}</a></address></div></div></section></main>
<footer class="section"><div class="footer-top"><a class="wordmark" href="#uvod">Viladům<span>v zahradách</span></a><span>Louny / Říjen 2026</span><a href="podklady-projektu.zip" download>Projektové podklady ke stažení</a></div><p>{AREA_NOTE} Aktuální nabídku, stav rekonstrukce, provedení a práva užívání společných částí potvrdí kontakt projektu.</p><details class="sources"><summary>Zdroje a platnost informací / {VERIFIED}</summary><ul>{source_links}</ul><p>Budoucí dopravní a městské investice jsou označené jako plány. Mapové odkazy vedou na konkrétní místa ve městě; nevyjadřují dochozí čas od domu.</p></details></footer>
<div class="mobile-contact" aria-label="Rychlý kontakt"><a href="tel:+420774320438">Zavolat</a><a href="{mail()}">Domluvit prohlídku</a></div>
<dialog id="viewer" aria-labelledby="viewer-caption"><div class="viewer-bar"><p id="viewer-caption"></p><a id="viewer-original" target="_blank" rel="noopener">Otevřít plné rozlišení</a><button id="close-viewer" autofocus>Zavřít</button></div><img id="viewer-image" alt=""></dialog><script src="brochure.js"></script>'''
(D/'index.html').write_text(head+body+'</body></html>')
(D/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: '+SITE_URL+'/sitemap.xml\n')
(D/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>'+SITE_URL+'/</loc><lastmod>2026-10-04</lastmod></url></urlset>')
public_data=[{'byt':u[0],'podlazi':u[1],'dispozice':u[2],'celkem_dle_projektu_m2':u[3],'mistnosti':u[5]} for u in UNITS]
(D/'projektova-data.json').write_text(json.dumps({'adresa_projektu':PROJECT_ADDRESS,'adresa_potvrzena_investorem':'4. 10. 2026','overeno':VERIFIED,'poznamka':AREA_NOTE,'byty':public_data,'zdroje':SOURCES},ensure_ascii=False,indent=2))
with zipfile.ZipFile(D/'podklady-projektu.zip','w',zipfile.ZIP_DEFLATED,compresslevel=8) as z:
 for path in sorted((D/'assets').glob('*.png')):
  if path.name not in ('social-card.png','map.png'):z.write(path,'projektove-vykresy/'+path.name)
 for path in sorted((D/'assets').glob('archviz-*.webp')):z.write(path,'materialove-pudorysy/'+path.name)
 z.write(D/'projektova-data.json','projektova-data.json')
 z.writestr('CTETE-PROSIM.txt',AREA_NOTE+'\n'+GARDEN_NOTE+'\nVýkresy pocházejí z původní brožury; nejde o potvrzení aktuálního provedení.\n')
print('Website built: 6 unchanged units, verified locality, direct contact and downloads.')
